/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Pedido;
import model.dao.PedidoDAO;

/**
 *
 * @author TeixeiraAdmin
 */
public class ConsultaPedidos extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaPedidos
     */
    public ConsultaPedidos() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tbPedido.getModel();
        tbPedido.setRowSorter(new TableRowSorter(modelo));
        
        readJTable();
    }
    public void readJTable() {
        // Este metodo serve para atualizar a tabela

        // Cria o modelo da tabela da forma padrao
        DefaultTableModel modelo = (DefaultTableModel) tbPedido.getModel();
        modelo.setNumRows(0);
        PedidoDAO usudao = new PedidoDAO();

        // Lê cada item do 'objpedido' e adiciona na lista 'tbRegistros'
        usudao.read().forEach((objpedido) -> {
            modelo.addRow(new Object[]{
                objpedido.getID(),
                objpedido.getIDItem(),
                objpedido.getNomeCliente(),
                objpedido.getCPFCliente(),
                objpedido.getNomeItem(),
                ("R$" + objpedido.getValor()),
                objpedido.getDataPedido()});
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbPedido = new javax.swing.JTable();
        btnRemoverPedido = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pedido", "IDItem", "NomeCliente", "CPFCliente", "NomeItem", "Valor", "Data e Hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPedido.getTableHeader().setReorderingAllowed(false);
        tbPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPedidoMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbPedidoMouseReleased(evt);
            }
        });
        tbPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbPedidoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbPedido);
        if (tbPedido.getColumnModel().getColumnCount() > 0) {
            tbPedido.getColumnModel().getColumn(0).setMinWidth(70);
            tbPedido.getColumnModel().getColumn(0).setPreferredWidth(70);
            tbPedido.getColumnModel().getColumn(0).setMaxWidth(70);
            tbPedido.getColumnModel().getColumn(1).setMinWidth(50);
            tbPedido.getColumnModel().getColumn(1).setPreferredWidth(50);
            tbPedido.getColumnModel().getColumn(1).setMaxWidth(50);
            tbPedido.getColumnModel().getColumn(2).setMinWidth(200);
            tbPedido.getColumnModel().getColumn(2).setPreferredWidth(200);
            tbPedido.getColumnModel().getColumn(2).setMaxWidth(200);
            tbPedido.getColumnModel().getColumn(3).setMinWidth(100);
            tbPedido.getColumnModel().getColumn(3).setPreferredWidth(100);
            tbPedido.getColumnModel().getColumn(3).setMaxWidth(100);
            tbPedido.getColumnModel().getColumn(4).setMinWidth(200);
            tbPedido.getColumnModel().getColumn(4).setPreferredWidth(200);
            tbPedido.getColumnModel().getColumn(4).setMaxWidth(200);
            tbPedido.getColumnModel().getColumn(6).setMinWidth(150);
            tbPedido.getColumnModel().getColumn(6).setPreferredWidth(150);
            tbPedido.getColumnModel().getColumn(6).setMaxWidth(150);
        }

        btnRemoverPedido.setText("Remover Pedido");
        btnRemoverPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverPedidoActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRemoverPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRemoverPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPedidoMouseClicked

    }//GEN-LAST:event_tbPedidoMouseClicked

    private void tbPedidoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPedidoMouseReleased

        btnRemoverPedido.setEnabled(true);
    }//GEN-LAST:event_tbPedidoMouseReleased

    private void tbPedidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbPedidoKeyReleased

    }//GEN-LAST:event_tbPedidoKeyReleased

    private void btnRemoverPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverPedidoActionPerformed
        // Remove a pedido indicada ao pressionar o botao Remover Pedido.
        if (tbPedido.getSelectedRow() != -1) {
            // Criando uma modificação para o MessageDIalog de aviso
            JFrame frame = new JFrame();
            String[] opcoesSMD = new String[2];
            opcoesSMD[0] = new String("Sim");
            opcoesSMD[1] = new String("Não");
            // Exibe o aviso e captura a resposta na variavel 'escolha'
            int escolha = JOptionPane.showOptionDialog(
                frame.getContentPane(),
                "O pedido selecionada sera removido!!!",
                "AVISO",
                0,
                JOptionPane.WARNING_MESSAGE,
                null,
                opcoesSMD,
                null);

            // Caso escolher opção "Sim", removerá a pedido selecionado da tabela
            if (escolha == JOptionPane.YES_OPTION) {

                // instanciando 'Pedido' e 'PedidoDAO'
                Pedido objpedido = new Pedido();
                PedidoDAO dao = new PedidoDAO();

                objpedido.setID((int) tbPedido.getValueAt(tbPedido.getSelectedRow(), 0));

                // Remove a pedido selecionado
                dao.delete(objpedido);
                readJTable();
                // Caso escolhar opçao "Não", nada sera alterado
            } else if (escolha == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "Nada foi alterado.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma pedido para remover");
        }
    }//GEN-LAST:event_btnRemoverPedidoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemoverPedido;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPedido;
    // End of variables declaration//GEN-END:variables
}
