/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.bean.Pedido;
import model.bean.Pessoa;
import model.bean.Produto;
import model.dao.PedidoDAO;
import model.dao.PessoaDAO;
import model.dao.ProdutoDAO;

/**
 *
 * @author rafael
 */
public class ViewPedido extends javax.swing.JFrame {

    /**
     * Creates new form ViewPedidos
     */
    public ViewPedido() {
        initComponents();

        btnAdicionarPedido.setEnabled(false);
        Pessoa pessoabean = new Pessoa();
        Produto produtobean = new Produto();

        Pedido objpedido = new Pedido();

        PessoaDAO pessoadao = new PessoaDAO();
        ProdutoDAO produtodao = new ProdutoDAO();

        cbCPFCliente.addItem("");
        cbIDItem.addItem("");
        int quantidadeItensSelecionados = 0;
        for (Pessoa people : pessoadao.read()) {
            cbCPFCliente.addItem(people.toString());
        }

        for (Produto product : produtodao.read()) {
            cbIDItem.addItem(product.getID());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCampos = new javax.swing.JPanel();
        lblVisualCPFCliente = new javax.swing.JLabel();
        lblVISUALITEM = new javax.swing.JLabel();
        cbCPFCliente = new javax.swing.JComboBox<>();
        cbIDItem = new javax.swing.JComboBox<>();
        lblNomeCliente = new javax.swing.JLabel();
        lblVISUALNOMECLIENTE = new javax.swing.JLabel();
        lblVISUALNOMEITEM = new javax.swing.JLabel();
        lblNomeItem = new javax.swing.JLabel();
        lblVISUALVALOR = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        btnProcurarCliente = new javax.swing.JButton();
        btnProcurarItem = new javax.swing.JButton();
        panelBotoes = new javax.swing.JPanel();
        btnSairCadastro = new javax.swing.JButton();
        btnAdicionarPedido = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnConsultarPedidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delivery");

        panelCampos.setBorder(javax.swing.BorderFactory.createTitledBorder("Gerenciar Pedidos"));

        lblVisualCPFCliente.setText("CPF Cliente");

        lblVISUALITEM.setText("Item");

        cbCPFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCPFClienteActionPerformed(evt);
            }
        });

        cbIDItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIDItemActionPerformed(evt);
            }
        });

        lblNomeCliente.setText("...");

        lblVISUALNOMECLIENTE.setText("Nome do Cliente:");

        lblVISUALNOMEITEM.setText("Nome do Item:");

        lblNomeItem.setText("...");

        lblVISUALVALOR.setText("Valor Total:");

        lblValor.setText("...");

        btnProcurarCliente.setText("Procurar");
        btnProcurarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarClienteActionPerformed(evt);
            }
        });

        btnProcurarItem.setText("Procurar");
        btnProcurarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCamposLayout = new javax.swing.GroupLayout(panelCampos);
        panelCampos.setLayout(panelCamposLayout);
        panelCamposLayout.setHorizontalGroup(
            panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblVisualCPFCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVISUALITEM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCamposLayout.createSequentialGroup()
                        .addComponent(cbIDItem, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProcurarItem)
                        .addGap(31, 31, 31)
                        .addComponent(lblVISUALNOMEITEM, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNomeItem, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(lblVISUALVALOR, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(panelCamposLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(cbCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProcurarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(lblVISUALNOMECLIENTE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        panelCamposLayout.setVerticalGroup(
            panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVisualCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVISUALNOMECLIENTE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProcurarCliente))
                .addGap(28, 28, 28)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVISUALITEM)
                    .addComponent(cbIDItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcurarItem)
                    .addComponent(lblVISUALNOMEITEM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNomeItem)
                    .addComponent(lblVISUALVALOR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblValor))
                .addGap(25, 25, 25))
        );

        btnSairCadastro.setText("Sair");
        btnSairCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCadastroActionPerformed(evt);
            }
        });

        btnAdicionarPedido.setText("Adicionar Pedido");
        btnAdicionarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPedidoActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnConsultarPedidos.setText("Consultar Pedidos");
        btnConsultarPedidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnConsultarPedidosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnConsultarPedidosFocusLost(evt);
            }
        });
        btnConsultarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotoesLayout = new javax.swing.GroupLayout(panelBotoes);
        panelBotoes.setLayout(panelBotoesLayout);
        panelBotoesLayout.setHorizontalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdicionarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnConsultarPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSairCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        panelBotoesLayout.setVerticalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotoesLayout.createSequentialGroup()
                        .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSairCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnConsultarPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCadastroActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairCadastroActionPerformed

    private void btnAdicionarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPedidoActionPerformed

        PedidoDAO pedidodao = new PedidoDAO();
        Pedido objpedido = new Pedido();
        Pessoa objpessoa = new Pessoa();
        Produto objproduto = new Produto();

        if (!"".equals(lblValor.getText())
                || !"".equals(lblNomeCliente.getText())
                || !"".equals(lblNomeItem.getText())) {

            int pedidoSelecionado = (int) cbIDItem.getSelectedItem();
            String CPFSelecionado = (String) cbCPFCliente.getSelectedItem();

            pedidodao.searchPessoa(CPFSelecionado, objpessoa);
            pedidodao.searchProduto(pedidoSelecionado, objproduto);

            //Todos os dados que irao pro registro na tabela Pedido
            pedidodao.create(objpessoa, objproduto);
        } else {
            JOptionPane.showMessageDialog(null, "Algum dado não foi informado!");
        }

    }//GEN-LAST:event_btnAdicionarPedidoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
        ViewPaginaInicial inicio = new ViewPaginaInicial();
        inicio.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnProcurarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarClienteActionPerformed
        if (cbCPFCliente.getSelectedItem() == "") {
            cbCPFCliente.setSelectedIndex(0);
            lblNomeCliente.setText("");
            JOptionPane.showMessageDialog(null, "Selecione um CPF!");

        } else {
            Pedido objpedido = new Pedido();
            String CPFSelecionado = (String) cbCPFCliente.getSelectedItem();

            PedidoDAO pedidodao = new PedidoDAO();
            Pessoa objpessoa = new Pessoa();
            pedidodao.searchPessoa(CPFSelecionado, objpessoa);
            objpedido.setNomeCliente(objpessoa.getNome());
            objpedido.setCPFCliente(objpessoa.getCPF());
            objpedido.setEndereco(objpessoa.getEndereco());
            objpedido.setTelefone(objpessoa.getTelefone());

            lblNomeCliente.setText(objpedido.getNomeCliente());

        }
        if (cbIDItem.getSelectedItem() != "" & cbCPFCliente.getSelectedItem() != "") {
            btnAdicionarPedido.setEnabled(true);
        } else {
            btnAdicionarPedido.setEnabled(false);
        }
    }//GEN-LAST:event_btnProcurarClienteActionPerformed

    private void btnProcurarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarItemActionPerformed
        if (cbIDItem.getSelectedItem() == "") {
            cbIDItem.setSelectedIndex(0);
            lblNomeItem.setText("");
            lblValor.setText("");
            JOptionPane.showMessageDialog(null, "Selecione um Item!");
        } else {
            PedidoDAO pedidodao = new PedidoDAO();
            Pedido objpedido = new Pedido();
            Produto objproduto = new Produto();

            try {
                int pedidoSelecionado = (int) cbIDItem.getSelectedItem();

                objpedido.setNomeItem(objpedido.getNomeItem());
                objpedido.setValor(objpedido.getValor());
                pedidodao.searchProduto(pedidoSelecionado, objproduto);
            } catch (java.lang.ClassCastException ex) {
                JOptionPane.showMessageDialog(null, "Selecione um produto!");
            }
            lblNomeItem.setText(objproduto.getNome());
            lblValor.setText("R$"+String.valueOf(objproduto.getPreco()));
        }
        if (cbIDItem.getSelectedIndex() != 0 & cbCPFCliente.getSelectedIndex() != 0) {
            btnAdicionarPedido.setEnabled(true);
        } else {
            btnAdicionarPedido.setEnabled(false);
        }


    }//GEN-LAST:event_btnProcurarItemActionPerformed

    private void cbIDItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIDItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIDItemActionPerformed

    private void cbCPFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCPFClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCPFClienteActionPerformed

    private void btnConsultarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPedidosActionPerformed
        this.dispose();
        ViewConsultaPedidos conspedido = new ViewConsultaPedidos();
        conspedido.setVisible(true);
        conspedido.readJTable();
    }//GEN-LAST:event_btnConsultarPedidosActionPerformed

    private void btnConsultarPedidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnConsultarPedidosFocusLost
        this.setEnabled(false);
    }//GEN-LAST:event_btnConsultarPedidosFocusLost

    private void btnConsultarPedidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnConsultarPedidosFocusGained
        this.setEnabled(true);
    }//GEN-LAST:event_btnConsultarPedidosFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarPedido;
    private javax.swing.JButton btnConsultarPedidos;
    private javax.swing.JButton btnProcurarCliente;
    private javax.swing.JButton btnProcurarItem;
    private javax.swing.JButton btnSairCadastro;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<Object> cbCPFCliente;
    private javax.swing.JComboBox<Object> cbIDItem;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeItem;
    private javax.swing.JLabel lblVISUALITEM;
    private javax.swing.JLabel lblVISUALNOMECLIENTE;
    private javax.swing.JLabel lblVISUALNOMEITEM;
    private javax.swing.JLabel lblVISUALVALOR;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblVisualCPFCliente;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelCampos;
    // End of variables declaration//GEN-END:variables
}
